ALL_ATTACK = {
    "Reconnaissance": {
        "T1595": "Active Scanning",
        "T1592": "Gather Victim Host Information",
        "T1589": "Gather Victim Identity Information",
        "T1590": "Gather Victim Network Information",
        "T1591": "Gather Victim Org Information",
        "T1598": "Phishing for Information",
        "T1597": "Search Closed Sources",
        "T1596": "Search Open Technical Databases",
        "T1593": "Search Open Websites/Domains",
        "T1594": "Search Victim-Owned Websites"
    },
    "Resource Development": {
        "T1583": "Acquire Infrastructure",
        "T1586": "Compromise Accounts",
        "T1584": "Compromise Infrastructure",
        "T1587": "Develop Capabilities",
        "T1585": "Establish Accounts",
        "T1588": "Obtain Capabilities",
        "T1608": "Stage Capabilities"
    },
    "Initial Access": {
        "T1189": "Drive-by Compromise",
        "T1190": "Exploit Public-Facing Application",
        "T1133": "External Remote Services",
        "T1200": "Hardware Additions",
        "T1566": "Phishing",
        "T1091": "Replication Through Removable Media",
        "T1195": "Supply Chain Compromise",
        "T1199": "Trusted Relationship",
        "T1078": "Valid Accounts"
    },
    "Execution": {
        "T1059": "Command and Scripting Interpreter",
        "T1609": "Container Administration Command",
        "T1610": "Deploy Container",
        "T1203": "Exploitation for Client Execution",
        "T1559": "Inter-Process Communication",
        "T1106": "Native API",
        "T1053": "Scheduled Task/Job",
        "T1129": "Shared Modules",
        "T1072": "Software Deployment Tools",
        "T1569": "System Services",
        "T1204": "User Execution",
        "T1047": "Windows Management Instrumentation"
    },
    "Persistence": {
        "T1098": "Account Manipulation",
        "T1197": "BITS Jobs",
        "T1547": "Boot or Logon Autostart Execution",
        "T1037": "Boot or Logon Initialization Scripts",
        "T1176": "Browser Extensions",
        "T1554": "Compromise Client Software Binary",
        "T1136": "Create Account",
        "T1543": "Create or Modify System Process",
        "T1546": "Event Triggered Execution",
        "T1133": "External Remote Services",
        "T1574": "Hijack Execution Flow",
        "T1525": "Implant Internal Image",
        "T1556": "Modify Authentication Process",
        "T1137": "Office Application Startup",
        "T1542": "Pre-OS Boot",
        "T1053": "Scheduled Task/Job",
        "T1505": "Server Software Component",
        "T1205": "Traffic Signaling",
        "T1078": "Valid Accounts"
    },
    "Privilege Escalation": {
        "T1548": "Abuse Elevation Control Mechanism",
        "T1134": "Access Token Manipulation",
        "T1547": "Boot or Logon Autostart Execution",
        "T1037": "Boot or Logon Initialization Scripts",
        "T1543": "Create or Modify System Process",
        "T1484": "Domain Policy Modification",
        "T1611": "Escape to Host",
        "T1546": "Event Triggered Execution",
        "T1068": "Exploitation for Privilege Escalation",
        "T1574": "Hijack Execution Flow",
        "T1055": "Process Injection",
        "T1053": "Scheduled Task/Job",
        "T1078": "Valid Accounts"
    },
    "Defense Evasion": {
        "T1548": "Abuse Elevation Control Mechanism",
        "T1134": "Access Token Manipulation",
        "T1197": "BITS Jobs",
        "T1612": "Build Image on Host",
        "T1140": "Deobfuscate/Decode Files or Information",
        "T1610": "Deploy Container",
        "T1006": "Direct Volume Access",
        "T1484": "Domain Policy Modification",
        "T1480": "Execution Guardrails",
        "T1211": "Exploitation for Defense Evasion",
        "T1222": "File and Directory Permissions Modification",
        "T1564": "Hide Artifacts",
        "T1574": "Hijack Execution Flow",
        "T1562": "Impair Defenses",
        "T1070": "Indicator Removal on Host",
        "T1202": "Indirect Command Execution",
        "T1036": "Masquerading",
        "T1556": "Modify Authentication Process",
        "T1578": "Modify Cloud Compute Infrastructure",
        "T1112": "Modify Registry",
        "T1601": "Modify System Image",
        "T1599": "Network Boundary Bridging",
        "T1027": "Obfuscated Files or Information",
        "T1542": "Pre-OS Boot",
        "T1055": "Process Injection",
        "T1620": "Reflective Code Loading",
        "T1207": "Rogue Domain Controller",
        "T1014": "Rootkit",
        "T1218": "Signed Binary Proxy Execution",
        "T1216": "Signed Script Proxy Execution",
        "T1553": "Subvert Trust Controls",
        "T1221": "Template Injection",
        "T1205": "Traffic Signaling",
        "T1127": "Trusted Developer Utilities Proxy Execution",
        "T1535": "Unused/Unsupported Cloud Regions",
        "T1550": "Use Alternate Authentication Material",
        "T1078": "Valid Accounts",
        "T1497": "Virtualization/Sandbox Evasion",
        "T1600": "Weaken Encryption",
        "T1220": "XSL Script Processing"
    },
    "Credential Access": {
        "T1557": "Adversary-in-the-Middle",
        "T1110": "Brute Force",
        "T1555": "Credentials from Password Stores",
        "T1212": "Exploitation for Credential Access",
        "T1187": "Forced Authentication",
        "T1606": "Forge Web Credentials",
        "T1056": "Input Capture",
        "T1556": "Modify Authentication Process",
        "T1040": "Network Sniffing",
        "T1003": "OS Credential Dumping",
        "T1528": "Steal Application Access Token",
        "T1539": "Steal Web Session Cookie",
        "T1558": "Steal or Forge Kerberos Tickets",
        "T1111": "Two-Factor Authentication Interception",
        "T1552": "Unsecured Credentials"
    },
    "Discovery": {
        "T1087": "Account Discovery",
        "T1010": "Application Window Discovery",
        "T1217": "Browser Bookmark Discovery",
        "T1580": "Cloud Infrastructure Discovery",
        "T1538": "Cloud Service Dashboard",
        "T1526": "Cloud Service Discovery",
        "T1619": "Cloud Storage Object Discovery",
        "T1613": "Container and Resource Discovery",
        "T1482": "Domain Trust Discovery",
        "T1083": "File and Directory Discovery",
        "T1615": "Group Policy Discovery",
        "T1046": "Network Service Scanning",
        "T1135": "Network Share Discovery",
        "T1040": "Network Sniffing",
        "T1201": "Password Policy Discovery",
        "T1120": "Peripheral Device Discovery",
        "T1069": "Permission Groups Discovery",
        "T1057": "Process Discovery",
        "T1012": "Query Registry",
        "T1018": "Remote System Discovery",
        "T1518": "Software Discovery",
        "T1082": "System Information Discovery",
        "T1614": "System Location Discovery",
        "T1016": "System Network Configuration Discovery",
        "T1049": "System Network Connections Discovery",
        "T1033": "System Owner/User Discovery",
        "T1007": "System Service Discovery",
        "T1124": "System Time Discovery",
        "T1497": "Virtualization/Sandbox Evasion"
    },
    "Lateral Movement": {
        "T1210": "Exploitation of Remote Services",
        "T1534": "Internal Spearphishing",
        "T1570": "Lateral Tool Transfer",
        "T1563": "Remote Service Session Hijacking",
        "T1021": "Remote Services",
        "T1091": "Replication Through Removable Media",
        "T1072": "Software Deployment Tools",
        "T1080": "Taint Shared Content",
        "T1550": "Use Alternate Authentication Material"
    },
    "Collection": {
        "T1557": "Adversary-in-the-Middle",
        "T1560": "Archive Collected Data",
        "T1123": "Audio Capture",
        "T1119": "Automated Collection",
        "T1185": "Browser Session Hijacking",
        "T1115": "Clipboard Data",
        "T1074": "Data Staged",
        "T1530": "Data from Cloud Storage Object",
        "T1602": "Data from Configuration Repository",
        "T1213": "Data from Information Repositories",
        "T1005": "Data from Local System",
        "T1039": "Data from Network Shared Drive",
        "T1025": "Data from Removable Media",
        "T1114": "Email Collection",
        "T1056": "Input Capture",
        "T1113": "Screen Capture",
        "T1125": "Video Capture"
    },
    "Command and Control": {
        "T1071": "Application Layer Protocol",
        "T1092": "Communication Through Removable Media",
        "T1132": "Data Encoding",
        "T1001": "Data Obfuscation",
        "T1568": "Dynamic Resolution",
        "T1573": "Encrypted Channel",
        "T1008": "Fallback Channels",
        "T1105": "Ingress Tool Transfer",
        "T1104": "Multi-Stage Channels",
        "T1095": "Non-Application Layer Protocol",
        "T1571": "Non-Standard Port",
        "T1572": "Protocol Tunneling",
        "T1090": "Proxy",
        "T1219": "Remote Access Software",
        "T1205": "Traffic Signaling",
        "T1102": "Web Service"
    },
    "Exfiltration": {
        "T1020": "Automated Exfiltration",
        "T1030": "Data Transfer Size Limits",
        "T1048": "Exfiltration Over Alternative Protocol",
        "T1041": "Exfiltration Over C2 Channel",
        "T1011": "Exfiltration Over Other Network Medium",
        "T1052": "Exfiltration Over Physical Medium",
        "T1567": "Exfiltration Over Web Service",
        "T1029": "Scheduled Transfer",
        "T1537": "Transfer Data to Cloud Account"
    },
    "Impact": {
        "T1531": "Account Access Removal",
        "T1485": "Data Destruction",
        "T1486": "Data Encrypted for Impact",
        "T1565": "Data Manipulation",
        "T1491": "Defacement",
        "T1561": "Disk Wipe",
        "T1499": "Endpoint Denial of Service",
        "T1495": "Firmware Corruption",
        "T1490": "Inhibit System Recovery",
        "T1498": "Network Denial of Service",
        "T1496": "Resource Hijacking",
        "T1489": "Service Stop",
        "T1529": "System Shutdown/Reboot"
    }
}

ALL_MBC = {
    "Anti-Behavioral Analysis": {
        "B0004": "Emulator Detection",
        "B0036": "Capture Evasion",
        "B0007": "Sandbox Detection",
        "B0003": "Dynamic Analysis Evasion",
        "B0008": "Executable Code Virtualization",
        "B0009": "Virtual Machine Detection",
        "B0005": "Emulator Evasion",
        "B0006": "Memory Dump Evasion",
        "B0001": "Debugger Detection",
        "B0025": "Conditional Execution",
        "B0002": "Debugger Evasion",
        "F0003": "Hooking",
        "F0001": "Software Packing"
    },
    "Anti-Static Analysis": {
        "B0008": "Executable Code Virtualization",
        "B0012": "Disassembler Evasion",
        "B0032": "Executable Code Obfuscation",
        "E1027": "Obfuscated Files or Information",
        "B0034": "Executable Code Optimization",
        "B0010": "Call Graph Generation Evasion",
        "B0045": "Data Flow Analysis Evasion",
        "F0001": "Software Packing"
    },
    "Collection": {
        "E1056": "Input Capture",
        "F0002": "Keylogging",
        "B0028": "Cryptocurrency",
        "F0003": "Hooking",
        "E1113": "Screen Capture"
    },
    "Command and Control": {
        "B0030": "C2 Communication",
        "B0031": "Domain Name Generation",
        "E1105": "Remote File Copy"
    },
    "Credential Access": {
        "E1056": "Input Capture",
        "F0002": "Keylogging",
        "B0028": "Cryptocurrency",
        "F0003": "Hooking",
        "E1113": "Screen Capture"
    },
    "Defense Evasion": {
        "F0005": "Hidden Files and Directories",
        "E1055": "Process Injection",
        "F0013": "Bootkit",
        "E1478": "Install Insecure or Malicious Configuration",
        "F0009": "Component Firmware",
        "B0037": "Bypass Data Execution Prevention",
        "F0007": "Self Deletion",
        "B0027": "Alternative Installation Location",
        "E1027": "Obfuscated Files or Information",
        "B0025": "Conditional Execution",
        "F0015": "Hijack Execution Flow",
        "E1014": "Rootkit",
        "E1112": "Modify Registry",
        "F0003": "Hooking",
        "F0006": "Indicator Blocking",
        "B0040": "Covert Location",
        "B0029": "Polymorphic Code",
        "E1564": "Hidden Artifacts",
        "F0004": "Disable or Evade Security Tools",
        "F0001": "Software Packing"
    },
    "Discovery": {
        "E1010": "Application Window Discovery",
        "B0046": "Code Discovery",
        "B0043": "Taskbar Discovery",
        "B0013": "Analysis Tool Discovery",
        "B0014": "SMTP Connection Discovery",
        "E1082": "System Information Discovery",
        "E1083": "File and Directory Discovery",
        "B0038": "Self Discovery"
    },
    "Execution": {
        "B0020": "Send Email",
        "B0021": "Send Poisoned Text Message",
        "B0024": "Prevent Concurrent Execution",
        "B0011": "Remote Commands",
        "E1203": "Exploitation for Client Execution",
        "E1204": "User Interaction",
        "E1059": "Command and Scripting Interpreter",
        "B0025": "Conditional Execution",
        "B0044": "Execution Dependency",
        "B0023": "Install Additional Program",
        "E1569": "System Services"
    },
    "Exfiltration": {
        "E1560": "Archive Collected Data",
        "E1020": "Automated Exfiltration"
    },
    "Impact": {
        "B0017": "Destroy Hardware",
        "E1190": "Exploit Kit Behavior",
        "E1485": "Data Destruction",
        "E1486": "Data Encrypted for Impact",
        "B0019": "Manipulate Network Traffic",
        "F0009": "Component Firmware",
        "F0014": "Disk Wipe",
        "E1203": "Exploitation for Client Execution",
        "B0039": "Spamming",
        "B0042": "Modify Hardware",
        "B0033": "Denial of Service",
        "B0016": "Compromise Data Integrity",
        "B0022": "Remote Access",
        "E1510": "Clipboard Modification",
        "B0018": "Resource Hijacking",
        "E1472": "Generate Fraudulent Advertising Revenue"
    },
    "Lateral Movement": {
        "B0020": "Send Email",
        "E1195": "Supply Chain Compromise",
        "B0026": "Malicious Network Driver",
        "B0021": "Send Poisoned Text Message",
        "E1105": "Remote File Copy"
    },
    "Communication": {
        "C0011": "DNS Communication",
        "C0012": "SMTP Communication",
        "C0004": "FTP Communication",
        "C0001": "Socket Communication",
        "C0005": "WinINet",
        "C0002": "HTTP Communication",
        "C0014": "ICMP Communication",
        "C0003": "Interprocess Communication"
    },
    "Cryptography": {
        "C0061": "Hashed Message Authentication Code",
        "C0031": "Decrypt Data",
        "C0029": "Cryptographic Hash",
        "C0021": "Generate Pseudo-random Sequence",
        "C0027": "Encrypt Data",
        "C0028": "Encryption Key",
        "C0059": "Crypto Library"
    },
    "Data": {
        "C0020": "Use Constant",
        "C0060": "Compression Library",
        "C0032": "Checksum",
        "C0030": "Non-Cryptographic Hash",
        "C0053": "Decode Data",
        "C0019": "Check String",
        "C0026": "Encode Data",
        "C0058": "Modulo",
        "C0024": "Compress Data",
        "C0025": "Decompress Data"
    },
    "File System": {
        "C0052": "Writes File",
        "C0049": "Get File Attributes",
        "C0046": "Create Directory",
        "C0015": "Alter File Extension",
        "C0063": "Move File",
        "C0050": "Set File Attributes",
        "C0016": "Create File",
        "C0056": "Read Virtual Disk",
        "C0051": "Read File",
        "C0045": "Copy File",
        "C0047": "Delete File",
        "C0048": "Delete Directory"
    },
    "Hardware": {
        "C0057": "Simulate Hardware",
        "C0023": "Load Driver",
        "C0037": "Install Driver"
    },
    "Memory": {
        "C0010": "Overflow Buffer",
        "C0008": "Change Memory Protection",
        "C0006": "Heap Spray",
        "C0007": "Allocate Memory",
        "C0009": "Stack Pivot",
        "C0044": "Free Memory"
    },
    "Operating System": {
        "C0035": "Wallpaper",
        "C0033": "Console",
        "C0034": "Environment Variable",
        "C0036": "Registry"
    },
    "Process": {
        "C0018": "Terminate Process",
        "C0055": "Suspend Thread",
        "C0017": "Create Process",
        "C0064": "Enumerate Threads",
        "C0038": "Create Thread",
        "C0039": "Terminate Thread",
        "C0043": "Check Mutex",
        "C0066": "Open Thread",
        "C0041": "Set Thread Local Storage Value",
        "C0065": "Open Process",
        "C0042": "Create Mutex",
        "C0022": "Synchronization",
        "C0054": "Resume Thread",
        "C0040": "Allocate Thread Local Storage"
    },
    "Persistence": {
        "F0005": "Hidden Files and Directories",
        "F0012": "Registry Run Keys / Startup Folder",
        "B0026": "Malicious Network Driver",
        "F0013": "Bootkit",
        "F0011": "Modify Existing Service",
        "E1478": "Install Insecure or Malicious Configuration",
        "F0009": "Component Firmware",
        "E1105": "Remote File Copy",
        "B0035": "Shutdown Event",
        "F0015": "Hijack Execution Flow",
        "B0022": "Remote Access",
        "E1112": "Modify Registry",
        "F0010": "Kernel Modules and Extensions",
        "F0003": "Hooking",
        "E1564": "Hidden Artifacts"
    },
    "Privilege Escalation": {
        "E1055": "Process Injection",
        "F0011": "Modify Existing Service",
        "F0015": "Hijack Execution Flow",
        "F0010": "Kernel Modules and Extensions",
        "F0003": "Hooking"
    }
}

VERDICTS = {
    "malicious": [
        "Anti-Behavioral Analysis::B0007",
        "Anti-Static Analysis::B0032",
        "Collection::T1123",
        "Collection::T1560",
        "Communication::C0014",
        "Credential Access::T1555",
        "Data::C0024",
        "Defense Evasion::F0004",
        "Defense Evasion::T1197",
        "Defense Evasion::T1548",
        "Discovery::T1615",
        "Hardware::C0057",
        "Impact::B0042",
        "Impact::E1485",
        "Impact::T1490",
        "Impact::T1499",
        "Impact::T1561",
        "Persistence::T1197"
    ],
    "suspicious": [
        "Anti-Behavioral Analysis::B0001",
        "Anti-Behavioral Analysis::B0004",
        "Anti-Behavioral Analysis::B0009",
        "Anti-Behavioral Analysis::B0025",
        "Anti-Static Analysis::B0012",
        "Collection::E1113",
        "Collection::F0002",
        "Collection::T1056",
        "Collection::T1113",
        "Collection::T1115",
        "Collection::T1125",
        "Collection::T1213",
        "Command and Control::B0030",
        "Communication::C0001",
        "Communication::C0002",
        "Communication::C0003",
        "Communication::C0004",
        "Communication::C0011",
        "Cryptography::C0021",
        "Cryptography::C0027",
        "Cryptography::C0028",
        "Cryptography::C0029",
        "Cryptography::C0031",
        "Cryptography::C0059",
        "Cryptography::C0061",
        "Data::C0019",
        "Data::C0025",
        "Data::C0026",
        "Data::C0030",
        "Data::C0032",
        "Data::C0060",
        "Defense Evasion::E1027",
        "Defense Evasion::E1055",
        "Defense Evasion::F0007",
        "Defense Evasion::F0015",
        "Defense Evasion::T1027",
        "Defense Evasion::T1055",
        "Defense Evasion::T1070",
        "Defense Evasion::T1112",
        "Defense Evasion::T1140",
        "Defense Evasion::T1222",
        "Defense Evasion::T1497",
        "Defense Evasion::T1553",
        "Defense Evasion::T1562",
        "Defense Evasion::T1564",
        "Defense Evasion::T1620",
        "Discovery::B0013",
        "Discovery::B0043",
        "Discovery::B0046",
        "Discovery::E1010",
        "Discovery::E1083",
        "Discovery::T1007",
        "Discovery::T1010",
        "Discovery::T1012",
        "Discovery::T1016",
        "Discovery::T1033",
        "Discovery::T1057",
        "Discovery::T1069",
        "Discovery::T1082",
        "Discovery::T1083",
        "Discovery::T1087",
        "Discovery::T1135",
        "Discovery::T1518",
        "Discovery::T1614",
        "Execution::B0023",
        "Execution::T1047",
        "Execution::T1059",
        "Execution::T1129",
        "Execution::T1569",
        "File System::C0045",
        "File System::C0046",
        "File System::C0047",
        "File System::C0048",
        "File System::C0049",
        "File System::C0050",
        "File System::C0051",
        "File System::C0052",
        "File System::C0063",
        "Impact::B0022",
        "Impact::E1510",
        "Impact::T1489",
        "Impact::T1496",
        "Impact::T1529",
        "Impact::T1531",
        "Memory::C0007",
        "Operating System::C0033",
        "Operating System::C0034",
        "Operating System::C0035",
        "Operating System::C0036",
        "Persistence::T1053",
        "Persistence::T1098",
        "Persistence::T1136",
        "Persistence::T1543",
        "Persistence::T1546",
        "Persistence::T1547",
        "Privilege Escalation::T1134",
        "Process::C0017",
        "Process::C0018",
        "Process::C0038",
        "Process::C0039",
        "Process::C0040",
        "Process::C0041",
        "Process::C0042",
        "Process::C0043",
        "Process::C0054",
        "Process::C0055",
        "Process::C0064"
    ]
}
